# Generated by Django 6.0.5 on 2026-06-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('produtor', 'Produtor'), ('veterinario', 'Veterinario'), ('estudante', 'Estudante'), ('pesquisador', 'Pesquisador'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('crmv', models.CharField(blank=True, max_length=40)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
