# Generated by Django 6.0.5 on 2026-06-02 11:57

from django.db import migrations, models


def change_outro_to_padrao(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(user_type='outro').update(user_type='padrao')


def change_padrao_to_outro(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(user_type='padrao').update(user_type='outro')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to='profiles/'),
        ),
        migrations.RunPython(change_outro_to_padrao, change_padrao_to_outro),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('padrao', 'Padrao'), ('produtor', 'Produtor'), ('veterinario', 'Veterinario'), ('estudante', 'Estudante'), ('pesquisador', 'Pesquisador')], default='padrao', max_length=30),
        ),
    ]
