# Generated by Django 6.0.5 on 2026-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_photo_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('produtor', 'Produtor'), ('veterinario', 'Veterinario'), ('estudante', 'Estudante'), ('pesquisador', 'Pesquisador')], default='padrao', max_length=30),
        ),
    ]
