# Generated by Django 6.0.5 on 2026-06-02 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tag', models.CharField(blank=True, max_length=80)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(blank=True, choices=[('macho', 'Macho'), ('femea', 'Femea')], max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('tratamento', 'Em tratamento'), ('vendido', 'Vendido'), ('obito', 'Obito')], default='ativo', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='pigs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='MedicationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=160)),
                ('active_principle', models.CharField(blank=True, max_length=160)),
                ('dose', models.CharField(blank=True, max_length=120)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('intramuscular', 'Intramuscular'), ('subcutanea', 'Subcutanea'), ('topica', 'Topica'), ('outra', 'Outra')], default='outra', max_length=30)),
                ('applied_at', models.DateField()),
                ('withdrawal_until', models.DateField(blank=True, null=True)),
                ('responsible', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='suinos.pig')),
            ],
            options={
                'ordering': ['-applied_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pig',
            constraint=models.UniqueConstraint(condition=models.Q(('tag', ''), _negated=True), fields=('owner', 'tag'), name='unique_pig_tag_per_owner'),
        ),
    ]
