# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suinos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pig",
            name="life_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leitao", "Leitao"),
                    ("creche", "Creche"),
                    ("crescimento", "Crescimento"),
                    ("terminacao", "Terminacao"),
                    ("matriz", "Matriz"),
                    ("reprodutor", "Reprodutor"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="pig",
            name="size_category",
            field=models.CharField(
                blank=True,
                choices=[("pequeno", "Pequeno"), ("medio", "Medio"), ("grande", "Grande")],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pig",
            name="pen",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="pig",
            name="origin",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
