# Generated by Django 6.0.5 on 2026-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=220, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=160)),
                ('fase_comum', models.CharField(blank=True, max_length=180)),
                ('sintomas_texto', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=180, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Variavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=220, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_comercial', models.CharField(max_length=220, unique=True)),
                ('principio_ativo', models.CharField(blank=True, max_length=260)),
                ('classe', models.CharField(blank=True, max_length=220)),
                ('indicacoes_principais', models.TextField(blank=True)),
                ('posologia', models.TextField(blank=True)),
                ('via_administracao', models.CharField(blank=True, max_length=220)),
                ('carencia', models.CharField(blank=True, max_length=220)),
                ('contraindicacoes', models.TextField(blank=True)),
                ('reacoes_adversas', models.TextField(blank=True)),
                ('mecanismo_acao', models.TextField(blank=True)),
                ('precaucoes', models.TextField(blank=True)),
                ('doencas_relacionadas', models.ManyToManyField(blank=True, related_name='farmacos', to='bulario.doenca')),
            ],
            options={
                'ordering': ['nome_comercial'],
            },
        ),
        migrations.AddField(
            model_name='doenca',
            name='sintomas',
            field=models.ManyToManyField(blank=True, related_name='doencas', to='bulario.sintoma'),
        ),
    ]
