# Generated by Django 6.0.5 on 2026-07-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_registros', models.PositiveIntegerField(default=1520)),
                ('semente', models.PositiveIntegerField(default=42)),
                ('arquivo', models.CharField(blank=True, max_length=500)),
                ('resumo', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('nome_comercial', models.CharField(max_length=220, unique=True)),
                ('tipo', models.CharField(blank=True, max_length=160)),
                ('doencas_prevenidas', models.TextField(blank=True)),
                ('agentes_alvo', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=160)),
                ('fase_indicada', models.CharField(blank=True, max_length=220)),
                ('idade_recomendada', models.CharField(blank=True, max_length=180)),
                ('dose', models.CharField(blank=True, max_length=180)),
                ('via', models.CharField(blank=True, max_length=120)),
                ('numero_doses', models.CharField(blank=True, max_length=80)),
                ('intervalo_reforco', models.CharField(blank=True, max_length=180)),
                ('inicio_imunidade', models.CharField(blank=True, max_length=180)),
                ('duracao_imunidade', models.CharField(blank=True, max_length=180)),
                ('carencia', models.CharField(blank=True, max_length=120)),
                ('armazenamento', models.CharField(blank=True, max_length=180)),
                ('contraindicacoes', models.TextField(blank=True)),
                ('reacoes_adversas', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nome_comercial'],
            },
        ),
        migrations.AddField(
            model_name='doenca',
            name='agente_etiologico',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='doenca',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='farmaco',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='variavel',
            name='opcoes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('sintomas', models.JSONField(default=list)),
                ('variaveis', models.JSONField(default=dict)),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_clinicos', to='bulario.doenca')),
                ('geracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='bulario.geracaodataset')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('geracao', 'numero'), name='caso_numero_por_geracao')],
            },
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicamento', models.CharField(max_length=220)),
                ('doenca_indicacao', models.CharField(max_length=260)),
                ('tipo', models.CharField(max_length=40)),
                ('prioridade', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicacoes', to='bulario.doenca')),
                ('farmaco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes', to='bulario.farmaco')),
                ('vacina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicacoes', to='bulario.vacina')),
            ],
            options={
                'ordering': ['medicamento', 'doenca_indicacao'],
                'constraints': [models.UniqueConstraint(fields=('medicamento', 'doenca_indicacao', 'tipo'), name='indicacao_unica')],
            },
        ),
    ]
